----------------------------------------------------
-------------HEALING SYSTEM SETUP-------------------
----------------------------------------------------

HEAL_DEFAULT_TEXTTAG_RED = 76.00
HEAL_DEFAULT_TEXTTAG_GREEN = 255.00
HEAL_DEFAULT_TEXTTAG_BLUE = 76.00
HEAL_DEFAULT_TEXTTAG_TRANSP = 0.00
HEAL_DEFAULT_TEXTTAG_FONTSIZE = 0.028
HEAL_DEFAULT_TEXTTAG_VELOC = 0.14
HEAL_DEFAULT_TEXTTAG_LIFES = 1.50
HEAL_DEFAULT_TEXTTAG_FADEP = 0
HEAL_RND_MULTIPLIER_LB = 0.99
HEAL_RND_MULTIPLIER_UB = 1.01
HEAL_DEFAULT_CRIT_MULTP = 1.50

HEALABS_DEFAULT_TEXTTAG_RED = 255.00
HEALABS_DEFAULT_TEXTTAG_GREEN = 76.00
HEALABS_DEFAULT_TEXTTAG_BLUE = 76.00
HEALABS_DEFAULT_TEXTTAG_TRANSP = 0.00
HEALABS_DEFAULT_TEXTTAG_FONTSIZE = 0.024
HEALABS_DEFAULT_TEXTTAG_VELOC = 0.14
HEALABS_DEFAULT_TEXTTAG_LIFES = 1.50
HEALABS_DEFAULT_TEXTTAG_FADEP = 0

healAbsorb = {}
healAbsorb_Unit = {}
healRecord = {}
healData = {}

healTxt = {
    red = HEAL_DEFAULT_TEXTTAG_RED
    ,green = HEAL_DEFAULT_TEXTTAG_GREEN
    ,blue = HEAL_DEFAULT_TEXTTAG_BLUE
    ,transp = HEAL_DEFAULT_TEXTTAG_TRANSP
    ,fontSize = HEAL_DEFAULT_TEXTTAG_FONTSIZE
    ,veloc = HEAL_DEFAULT_TEXTTAG_VELOC
    ,lifes = HEAL_DEFAULT_TEXTTAG_LIFES
    ,fadep = HEAL_DEFAULT_TEXTTAG_FADEP
}

healabsTxt = {
    red = HEALABS_DEFAULT_TEXTTAG_RED
    ,green = HEALABS_DEFAULT_TEXTTAG_GREEN
    ,blue = HEALABS_DEFAULT_TEXTTAG_BLUE
    ,transp = HEALABS_DEFAULT_TEXTTAG_TRANSP
    ,fontSize = HEALABS_DEFAULT_TEXTTAG_FONTSIZE
    ,veloc = HEALABS_DEFAULT_TEXTTAG_VELOC
    ,lifes = HEALABS_DEFAULT_TEXTTAG_LIFES
    ,fadep = HEALABS_DEFAULT_TEXTTAG_FADEP
}